name: Test and Lint

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.6.0
      - name: Run Biome
        run: biome ci ./src server.ts

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
