name: Test and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.6.0
      - name: Run Biome
        run: biome ci ./src server.ts

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  e2e:
    needs: [build, lint]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Start server and test
        run: pnpm test:e2e
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

  test:
    needs: [e2e]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
          cache: "pnpm"
      - uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test

      